---
name: REST-Google
version: 1.0.1
author:
  - 'Eugen Sobchenko <ejs@cpan.org>'
abstract: access Google REST API from Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Data::Inheritable: 0.06
  JSON::Any: 1.16
  LWP::UserAgent: 2.033
  Test::More: 0.47
  URI: 1.35
  perl: 5.6.1
  version: 0.50
provides:
  REST::Google:
    file: lib/REST/Google.pm
    version: 1.0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
